build:
  lint-and-test:
    image: node:6
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      - npm i
      - npm run lint
      - npm test

cache:
  mount:
    - /drone/.npm
