build:
  lint-and-test:
    image: node:6
    environment:
      - NPM_CONFIG_CACHE=/drone/.npm
      - NPM_CONFIG_LOGLEVEL=warn
    commands:
      ## required for running flow
      - apt-get update -qq
      - apt-get install -qy libelf1
      - npm i
      - npm run lint
      - npm run flow
      - npm test

cache:
  mount:
    - /drone/.npm
